### ISSUE TITLE
Could you describe a little more detailed?

### ISSUE THREAD

**Issue by khoi-thinh** [franciskim/slackweatherbot#1]
1.What is eventemitter3, jethro, request and ws. How to install them?
2.After running node example_bot.js, what's do to next? Do i have to turn it off or open another windows and use this command: npm install slackweatherbot
3. Afer that,i bot the following script in the weatherbot.js 
var slackweatherbot = require('slackweatherbot');
weatherBot = new slackweatherbot();
But Within the switch statement place the following code: I don't find any "switch". Could you point it out to me, please?

**Comment by franciskim** [comment]
1. That's a question for this repo: https://github.com/xBytez/slackbotapi/ but you don't need to know about them generally.
   2 & 3. The example_bot.js should contain a switch statement. It's also linked to the exact line from my repo readme.
